all:
	g++ sqlite.cpp -o db.out -lsqlite3 -L/home/hanjinying/app/sqlite-snapshot-201710041413/.libs 
	g++ CppSQLite3*.cpp -o lite3.out -w -lsqlite3 -L/home/hanjinying/app/sqlite-snapshot-201710041413/.libs 
clean:
	rm *.out
